### PR TITLE
Added support for PermaProps

### PR DESCRIPTION
**Pull request by creator2013**
Added support for PermaProps.

First attempt failed. The check for the BoardData is now in the timer, which means that it can't check for the BoardData before PermaProps adds the saved data to the entity.

### CODE REVIEW

**Comment by JeremeyKingrey** [comment]
This does not work.

**Comment by RickyBGamez** [comment]
Once again, it failed to save any information for that entity.

I watched @JeremeyKingrey test it, and it fully broke his server. I'm not aware of what he used to test it, he can comment on what he tested it on.

I've once again tested it on multiple gamemodes (Sandbox, DarkRP, and my custom development gamemode) with the PermaProps tool from workshop. Placed down 1 board, tested it, and it didn't save. Tried multiple, and it didn't save. What I'm noticing is that it's failing to save board data for PermaProps. So, from my test, it appears still to be failing to save data.

**Comment by creator2013** [comment]
That's strange. 
A friend of mine tested it on his dedicated server and at first it didn't work but he had PermaProps 3.0 installed on his server. When he updated PermaProps to 4.0 it worked for him.

I can't tell why @JeremeyKingrey server is crashing. A console or crash log would be helpful

**Comment by JeremeyKingrey** [comment]
The server did not crash, it simply did not work. Later today, I will try to find you the error.

**Comment by creator2013** [comment]
My friend looked over the code and he didn't find any error. The only thing he noticed is that the table PermaProps is nil when you use a version that is older than version 4.0.

**Comment by RickyBGamez** [comment]
I'm using PermaProps 4.0 on all servers that it was tested on.

**Pull request closed without merging**
